server:
  port: 8080

---

server:
  port: 8081

spring:
  profiles: default
  datasource:
    url: jdbc:mysql://localhost:3306/MUNGTA?serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: skcc10633
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:29092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: pet
          destination: petstore
          contentType: application/json
        event-out:
          destination: petstore
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

---


spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: pet
          destination: petstore
          contentType: application/json
        event-out:
          destination: petstore
          contentType: application/json
